=== Amjad-Afzaal/RTPL-pc-side-code/pc-side-code/src/xml/KeepReferenceXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/KeepReferenceXMLSchema"
            xmlns:tns="http://xml.netbeans.org/schema/KeepReferenceXMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="KeepReference">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Package" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence/>
                        <xsd:attribute name="name" type="xsd:string"/>
                        <xsd:attribute name="includeSubPackages" type="xsd:boolean"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="ClassFile" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Function" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence/>
                                    <xsd:attribute name="name" type="xsd:string"/>
                                    <xsd:attribute name="description" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Field" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence/>
                                    <xsd:attribute name="name" type="xsd:string"/>
                                    <xsd:attribute name="description" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string"/>
                        <xsd:attribute name="includeAllFunctions" type="xsd:boolean"/>
                        <xsd:attribute name="includeAllFields" type="xsd:boolean"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Amjad-Afzaal/RTPL-pc-side-code/pc-side-code/run/KeepReferenceXML.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : KeepReferenceXMLSchema.xml
    Created on : 4. November 2008, 12:11
    Author     : aslam
    Description:
        Purpose of the document follows.
-->

<ns0:KeepReference  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/KeepReferenceXMLSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/KeepReferenceXMLSchema KeepReferenceXMLSchema.xsd'>
	
 <!--<ns0:Package name="*" includeSubPackages="true"/>-->
 
 <!-- keep Main.class -->

  <!-- <ns0:ClassFile name="Main" includeAllFunctions="false" includeAllFields="false"> -->
  <!-- 	<ns0:Function name="main" description="([Ljava/lang/String;)V"/> -->
  <!-- </ns0:ClassFile> -->


 <!-- Following classes are required by JVM -->
  <ns0:ClassFile name="takatuka/vm/VM" includeAllFunctions="false" includeAllFields="false">
  	<ns0:Function name="initialize" description="()V"/>
	<ns0:Function name="registerStatics" description="()V"/>
  </ns0:ClassFile>
  <ns0:ClassFile name="java/lang/Thread" includeAllFunctions="false" includeAllFields="true">
	<ns0:Function name="run" description="()V"/>
  </ns0:ClassFile>  
  <ns0:ClassFile name="java/lang/Object" includeAllFunctions="false" includeAllFields="true"/>
  <ns0:ClassFile name="java/lang/String" includeAllFunctions="false" includeAllFields="false">
	<ns0:Field name="value" description="[C"/>
	<ns0:Field name="offset" description="I"/>
	<ns0:Field name="count" description="I"/>
  </ns0:ClassFile>  
  <ns0:ClassFile name="takatuka/vm/ExceptionFactory" includeAllFunctions="true" includeAllFields="true"/>
  <ns0:ClassFile name="takatuka/vm/StaticInitializer" includeAllFunctions="true" includeAllFields="true"/>



</ns0:KeepReference>
